import type { INodeProperties } from 'n8n-workflow';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const advisorOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
			},
		},
		options: [
			{
				name: 'Apply Finding',
				value: 'apply',
				action: 'Apply an advisor finding',
				description: 'Apply an advisor finding',
			},
			{
				name: 'Dismiss Finding',
				value: 'dismiss',
				action: 'Dismiss an advisor finding',
				description: 'Dismiss an advisor finding',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many advisor findings',
				description: 'Get many advisor findings',
			},
			{
				name: 'Get Settings',
				value: 'getSettings',
				action: 'Get advisor settings',
				description: 'Get advisor settings',
			},
			{
				name: 'Get Summary',
				value: 'getSummary',
				action: 'Get the advisor summary',
				description: 'Get the advisor summary',
			},
			{
				name: 'Refresh',
				value: 'refresh',
				action: 'Refresh advisor findings',
				description: 'Refresh advisor findings',
			},
			{
				name: 'Snooze Finding',
				value: 'snooze',
				action: 'Snooze an advisor finding',
				description: 'Snooze an advisor finding',
			},
			{
				name: 'Submit Feedback',
				value: 'submitFeedback',
				action: 'Submit feedback on an advisor finding',
				description: 'Submit feedback on an advisor finding',
			},
			{
				name: 'Undo Finding',
				value: 'undo',
				action: 'Undo an applied advisor finding',
				description: 'Undo an applied advisor finding',
			},
		],
		default: 'getAll',
	},
];

export const advisorFields: INodeProperties[] = [
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The recommendation\'s id',
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'apply',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'apply',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The recommendation\'s id',
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'dismiss',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'dismiss',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Reason',
				name: 'reason',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'getAll',
				],
			},
		},
		options: [
			{
				displayName: 'Category',
				name: 'category',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Entity ID',
				name: 'entity_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Entity Type',
				name: 'entity_type',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Surface',
				name: 'surface',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'refresh',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The recommendation\'s id',
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'snooze',
				],
			},
		},
	},
	{
		displayName: 'Days',
		name: 'days',
		type: 'number',
		default: 0,
		required: true,
		description: 'Days must be 1-90. Anything else is rejected: an unbounded snooze is a dismissal wearing a disguise, and the two should stay distinguishable.',
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'snooze',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'snooze',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'submitFeedback',
				],
			},
		},
	},
	{
		displayName: 'Helpful',
		name: 'helpful',
		type: 'boolean',
		default: false,
		required: true,
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'submitFeedback',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'submitFeedback',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Reason',
				name: 'reason',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The recommendation\'s id',
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'undo',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'advisor',
				],
				operation: [
					'undo',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
];
