import type { INodeProperties } from 'n8n-workflow';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const agentToolOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [
					'agentTool',
				],
			},
		},
		options: [
			{
				name: 'Call',
				value: 'call',
				action: 'Call an agent tool',
				description: 'Call an agent tool',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many agent tools',
				description: 'Get many agent tools',
			},
		],
		default: 'getAll',
	},
];

export const agentToolFields: INodeProperties[] = [
	{
		displayName: 'Arguments',
		name: 'arguments',
		type: 'json',
		default: '',
		required: true,
		description: 'Provide as JSON.',
		displayOptions: {
			show: {
				resource: [
					'agentTool',
				],
				operation: [
					'call',
				],
			},
		},
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		required: true,
		description: 'The tool name from the list endpoint.',
		displayOptions: {
			show: {
				resource: [
					'agentTool',
				],
				operation: [
					'call',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'agentTool',
				],
				operation: [
					'call',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'agentTool',
				],
				operation: [
					'getAll',
				],
			},
		},
		options: [
			{
				displayName: 'Format',
				name: 'format',
				type: 'options',
				options: [
					{
						name: 'Functions',
						value: 'functions',
					},
					{
						name: 'Hermes',
						value: 'hermes',
					},
					{
						name: 'Openai',
						value: 'openai',
					},
					{
						name: 'Warmbly',
						value: 'warmbly',
					},
				],
				default: 'warmbly',
				description: 'Manifest format.',
			},
		],
	},
];
