import type { INodeProperties } from 'n8n-workflow';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const formOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [
					'form',
				],
			},
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a form',
				description: 'Create a form',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a form',
				description: 'Delete a form',
			},
			{
				name: 'Delete Asset',
				value: 'deleteAsset',
				action: 'Delete a form asset',
				description: 'Delete a form asset',
			},
			{
				name: 'Delete Submission',
				value: 'deleteSubmission',
				action: 'Delete a form submission',
				description: 'Delete a form submission',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a form',
				description: 'Get a form',
			},
			{
				name: 'Get Config',
				value: 'getConfig',
				action: 'Get the forms configuration',
				description: 'Get the forms configuration',
			},
			{
				name: 'Get Domain',
				value: 'getDomain',
				action: 'Get the forms domain',
				description: 'Get the forms domain',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many forms',
				description: 'Get many forms',
			},
			{
				name: 'Get Prefilled Link',
				value: 'getLink',
				action: 'Mint a prefilled form link',
				description: 'Mint a prefilled form link',
			},
			{
				name: 'Get Stats',
				value: 'getStats',
				action: 'Get form statistics',
				description: 'Get form statistics',
			},
			{
				name: 'Get Submissions',
				value: 'getSubmissions',
				action: 'Get many form submissions',
				description: 'Get many form submissions',
			},
			{
				name: 'Set Domain',
				value: 'setDomain',
				action: 'Set the forms domain',
				description: 'Set the forms domain',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a form',
				description: 'Update a form',
			},
			{
				name: 'Upload Asset',
				value: 'uploadAsset',
				action: 'Upload a form asset',
				description: 'Upload a form asset',
			},
			{
				name: 'Verify Domain',
				value: 'verifyDomain',
				action: 'Verify the forms domain',
				description: 'Verify the forms domain',
			},
		],
		default: 'getAll',
	},
];

export const formFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'create',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Form name',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The form\'s id',
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'delete',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'delete',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'deleteAsset',
				],
			},
		},
	},
	{
		displayName: 'Kind',
		name: 'kind',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'deleteAsset',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'deleteAsset',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'deleteSubmission',
				],
			},
		},
	},
	{
		displayName: 'Step ID',
		name: 'sid',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'deleteSubmission',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'deleteSubmission',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The form\'s id',
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'get',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'getLink',
				],
			},
		},
	},
	{
		displayName: 'Contact ID',
		name: 'contactID',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'getLink',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The form\'s id',
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'getStats',
				],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'getStats',
				],
			},
		},
		options: [
			{
				displayName: 'Range',
				name: 'range',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The form\'s id',
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'getSubmissions',
				],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'getSubmissions',
				],
			},
		},
		options: [
			{
				displayName: 'Before',
				name: 'before',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'setDomain',
				],
			},
		},
		options: [
			{
				displayName: 'Forms Domain',
				name: 'forms_domain',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The form\'s id',
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'update',
				],
			},
		},
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'update',
				],
			},
		},
		options: [
			{
				displayName: 'Allowed Domains',
				name: 'allowed_domains',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Campaign ID',
				name: 'campaign_id',
				type: 'json',
				default: '',
				description: 'Provide as JSON.',
			},
			{
				displayName: 'Captcha Enabled',
				name: 'captcha_enabled',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Category IDs',
				name: 'category_ids',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Design',
				name: 'design',
				type: 'json',
				default: '',
				description: 'Provide as JSON.',
			},
			{
				displayName: 'Fields',
				name: 'fields',
				type: 'json',
				default: '',
				description: 'Provide as JSON.',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Form name',
			},
			{
				displayName: 'Redirect URL',
				name: 'redirect_url',
				type: 'string',
				default: '',
				description: 'Where to send a visitor after submitting',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{
						name: 'Archived',
						value: 'archived',
					},
					{
						name: 'Draft',
						value: 'draft',
					},
					{
						name: 'Published',
						value: 'published',
					},
				],
				default: 'draft',
				description: 'draft or published',
			},
			{
				displayName: 'Success Message',
				name: 'success_message',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'uploadAsset',
				],
			},
		},
	},
	{
		displayName: 'Kind',
		name: 'kind',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'uploadAsset',
				],
			},
		},
	},
	{
		displayName: 'Input Binary Field',
		name: 'binaryPropertyName',
		type: 'string',
		default: 'data',
		required: true,
		description: 'The name of the input binary field holding the file to upload',
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'uploadAsset',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'uploadAsset',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'form',
				],
				operation: [
					'verifyDomain',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
];
