import type { INodeProperties } from 'n8n-workflow';

import { advisorOperations, advisorFields } from './advisor';
import { agentToolOperations, agentToolFields } from './agentTool';
import { aiSkillOperations, aiSkillFields } from './aiSkill';
import { analyticsOperations, analyticsFields } from './analytics';
import { apiKeyOperations, apiKeyFields } from './apiKey';
import { auditLogOperations, auditLogFields } from './auditLog';
import { automationOperations, automationFields } from './automation';
import { campaignOperations, campaignFields } from './campaign';
import { campaignVariantOperations, campaignVariantFields } from './campaignVariant';
import { folderOperations, folderFields } from './folder';
import { campaignStepOperations, campaignStepFields } from './campaignStep';
import { contactOperations, contactFields } from './contact';
import { contactCategoryOperations, contactCategoryFields } from './contactCategory';
import { contactNoteOperations, contactNoteFields } from './contactNote';
import { crmTaskOperations, crmTaskFields } from './crmTask';
import { crmTaskTypeOperations, crmTaskTypeFields } from './crmTaskType';
import { deadLetterOperations, deadLetterFields } from './deadLetter';
import { dealOperations, dealFields } from './deal';
import { deliverabilityOperations, deliverabilityFields } from './deliverability';
import { formOperations, formFields } from './form';
import { integrationOperations, integrationFields } from './integration';
import { leadSyncOperations, leadSyncFields } from './leadSync';
import { mailboxOperations, mailboxFields } from './mailbox';
import { mailboxTagOperations, mailboxTagFields } from './mailboxTag';
import { meetingOperations, meetingFields } from './meeting';
import { oauthAppOperations, oauthAppFields } from './oauthApp';
import { outreachOperations, outreachFields } from './outreach';
import { pipelineOperations, pipelineFields } from './pipeline';
import { templateOperations, templateFields } from './template';
import { segmentOperations, segmentFields } from './segment';
import { suppressionOperations, suppressionFields } from './suppression';
import { teamOperations, teamFields } from './team';
import { uniboxOperations, uniboxFields } from './unibox';
import { warmupRoutingOperations, warmupRoutingFields } from './warmupRouting';
import { webhookOperations, webhookFields } from './webhook';
import { workspaceOperations, workspaceFields } from './workspace';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const resourceProperty: INodeProperties = {
	displayName: 'Resource',
	name: 'resource',
	type: 'options',
	noDataExpression: true,
	options: [
		{
			name: 'Advisor',
			value: 'advisor',
		},
		{
			name: 'Agent Tool',
			value: 'agentTool',
		},
		{
			name: 'AI Skill',
			value: 'aiSkill',
		},
		{
			name: 'Analytics',
			value: 'analytics',
		},
		{
			name: 'API Key',
			value: 'apiKey',
		},
		{
			name: 'Audit Log',
			value: 'auditLog',
		},
		{
			name: 'Automation',
			value: 'automation',
		},
		{
			name: 'Campaign',
			value: 'campaign',
		},
		{
			name: 'Campaign A/B Variant',
			value: 'campaignVariant',
		},
		{
			name: 'Campaign Folder',
			value: 'folder',
		},
		{
			name: 'Campaign Step',
			value: 'campaignStep',
		},
		{
			name: 'Contact',
			value: 'contact',
		},
		{
			name: 'Contact Category',
			value: 'contactCategory',
		},
		{
			name: 'Contact Note',
			value: 'contactNote',
		},
		{
			name: 'CRM Task',
			value: 'crmTask',
		},
		{
			name: 'CRM Task Type',
			value: 'crmTaskType',
		},
		{
			name: 'Dead Letter',
			value: 'deadLetter',
		},
		{
			name: 'Deal',
			value: 'deal',
		},
		{
			name: 'Deliverability',
			value: 'deliverability',
		},
		{
			name: 'Form',
			value: 'form',
		},
		{
			name: 'Integration',
			value: 'integration',
		},
		{
			name: 'Lead Sync Source',
			value: 'leadSync',
		},
		{
			name: 'Mailbox',
			value: 'mailbox',
		},
		{
			name: 'Mailbox Tag',
			value: 'mailboxTag',
		},
		{
			name: 'Meeting',
			value: 'meeting',
		},
		{
			name: 'OAuth Application',
			value: 'oauthApp',
		},
		{
			name: 'Outreach Settings',
			value: 'outreach',
		},
		{
			name: 'Pipeline',
			value: 'pipeline',
		},
		{
			name: 'Reply Template',
			value: 'template',
		},
		{
			name: 'Segment',
			value: 'segment',
		},
		{
			name: 'Suppression',
			value: 'suppression',
		},
		{
			name: 'Team',
			value: 'team',
		},
		{
			name: 'Unibox',
			value: 'unibox',
		},
		{
			name: 'Warmup Routing Rule',
			value: 'warmupRouting',
		},
		{
			name: 'Webhook',
			value: 'webhook',
		},
		{
			name: 'Workspace',
			value: 'workspace',
		},
	],
	default: 'campaign',
};

export const operationProperties: INodeProperties[] = [
	...advisorOperations,
	...agentToolOperations,
	...aiSkillOperations,
	...analyticsOperations,
	...apiKeyOperations,
	...auditLogOperations,
	...automationOperations,
	...campaignOperations,
	...campaignVariantOperations,
	...folderOperations,
	...campaignStepOperations,
	...contactOperations,
	...contactCategoryOperations,
	...contactNoteOperations,
	...crmTaskOperations,
	...crmTaskTypeOperations,
	...deadLetterOperations,
	...dealOperations,
	...deliverabilityOperations,
	...formOperations,
	...integrationOperations,
	...leadSyncOperations,
	...mailboxOperations,
	...mailboxTagOperations,
	...meetingOperations,
	...oauthAppOperations,
	...outreachOperations,
	...pipelineOperations,
	...templateOperations,
	...segmentOperations,
	...suppressionOperations,
	...teamOperations,
	...uniboxOperations,
	...warmupRoutingOperations,
	...webhookOperations,
	...workspaceOperations,
];

export const fieldProperties: INodeProperties[] = [
	...advisorFields,
	...agentToolFields,
	...aiSkillFields,
	...analyticsFields,
	...apiKeyFields,
	...auditLogFields,
	...automationFields,
	...campaignFields,
	...campaignVariantFields,
	...folderFields,
	...campaignStepFields,
	...contactFields,
	...contactCategoryFields,
	...contactNoteFields,
	...crmTaskFields,
	...crmTaskTypeFields,
	...deadLetterFields,
	...dealFields,
	...deliverabilityFields,
	...formFields,
	...integrationFields,
	...leadSyncFields,
	...mailboxFields,
	...mailboxTagFields,
	...meetingFields,
	...oauthAppFields,
	...outreachFields,
	...pipelineFields,
	...templateFields,
	...segmentFields,
	...suppressionFields,
	...teamFields,
	...uniboxFields,
	...warmupRoutingFields,
	...webhookFields,
	...workspaceFields,
];
