import type { INodeProperties } from 'n8n-workflow';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const leadSyncOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
			},
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a lead sync source',
				description: 'Create a lead sync source',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a lead sync source',
				description: 'Delete a lead sync source',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a lead sync source',
				description: 'Get a lead sync source',
			},
			{
				name: 'Get Google Connection',
				value: 'getGoogleConnection',
				action: 'Get the Google Sheets connection',
				description: 'Get the Google Sheets connection',
			},
			{
				name: 'Get Google Spreadsheet',
				value: 'getGoogleSpreadsheet',
				action: 'Get a Google spreadsheet',
				description: 'Get a Google spreadsheet',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many lead sync sources',
				description: 'Get many lead sync sources',
			},
			{
				name: 'Preview Google Sheet',
				value: 'previewGoogleSheet',
				action: 'Preview a Google Sheet import',
				description: 'Preview a Google Sheet import',
			},
			{
				name: 'Sync Now',
				value: 'sync',
				action: 'Sync a lead source now',
				description: 'Sync a lead source now',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a lead sync source',
				description: 'Update a lead sync source',
			},
		],
		default: 'getAll',
	},
];

export const leadSyncFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'create',
				],
			},
		},
		options: [
			{
				displayName: 'Category IDs',
				name: 'category_ids',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Column Mapping',
				name: 'column_mapping',
				type: 'json',
				default: '',
				description: 'Provide as JSON.',
			},
			{
				displayName: 'Connection ID',
				name: 'connection_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Dedup',
				name: 'dedup',
				type: 'options',
				options: [
					{
						name: 'Create Duplicate',
						value: 'create_duplicate',
					},
					{
						name: 'Skip',
						value: 'skip',
					},
					{
						name: 'Update',
						value: 'update',
					},
				],
				default: 'skip',
			},
			{
				displayName: 'Has Header',
				name: 'has_header',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Label',
				name: 'label',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Sheet ID',
				name: 'sheet_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Sheet Title',
				name: 'sheet_title',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Subscribed Default',
				name: 'subscribed_default',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Tab Title',
				name: 'tab_title',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Target Campaign ID',
				name: 'target_campaign_id',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'delete',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'delete',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'get',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'getGoogleSpreadsheet',
				],
			},
		},
		options: [
			{
				displayName: 'Connection ID',
				name: 'connection_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Sheet ID',
				name: 'sheet_id',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'getAll',
				],
			},
		},
		options: [
			{
				displayName: 'Campaign ID',
				name: 'campaign_id',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'previewGoogleSheet',
				],
			},
		},
		options: [
			{
				displayName: 'Connection ID',
				name: 'connection_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Sheet ID',
				name: 'sheet_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Tab Title',
				name: 'tab_title',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'sync',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'sync',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'update',
				],
			},
		},
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'leadSync',
				],
				operation: [
					'update',
				],
			},
		},
		options: [
			{
				displayName: 'Category IDs',
				name: 'category_ids',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Clear Campaign',
				name: 'clear_campaign',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Column Mapping',
				name: 'column_mapping',
				type: 'json',
				default: '',
				description: 'Provide as JSON.',
			},
			{
				displayName: 'Dedup',
				name: 'dedup',
				type: 'options',
				options: [
					{
						name: 'Create Duplicate',
						value: 'create_duplicate',
					},
					{
						name: 'Skip',
						value: 'skip',
					},
					{
						name: 'Update',
						value: 'update',
					},
				],
				default: 'skip',
			},
			{
				displayName: 'Has Header',
				name: 'has_header',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Label',
				name: 'label',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Sheet ID',
				name: 'sheet_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Sheet Title',
				name: 'sheet_title',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Subscribed Default',
				name: 'subscribed_default',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Tab Title',
				name: 'tab_title',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Target Campaign ID',
				name: 'target_campaign_id',
				type: 'string',
				default: '',
			},
		],
	},
];
