import type { INodeProperties } from 'n8n-workflow';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const mailboxOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
			},
		},
		options: [
			{
				name: 'Bulk Tag',
				value: 'bulkTag',
				action: 'Tag many mailboxes',
				description: 'Tag many mailboxes',
			},
			{
				name: 'Check Domain Authentication',
				value: 'authCheck',
				action: 'Check domain authentication',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a mailbox',
				description: 'Delete a mailbox',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a mailbox',
				description: 'Get a mailbox',
			},
			{
				name: 'Get Allowance',
				value: 'getAllowance',
				action: 'Get the mailbox allowance',
				description: 'Get the mailbox allowance',
			},
			{
				name: 'Get Behavior',
				value: 'getBehavior',
				action: 'Get sending behavior',
				description: 'Get sending behavior',
			},
			{
				name: 'Get Behavior Plan',
				value: 'getBehaviorPlan',
				action: 'Get the sending behavior plan',
				description: 'Get the sending behavior plan',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many mailboxes',
				description: 'Get many mailboxes',
			},
			{
				name: 'Get Sync Status',
				value: 'getSyncStatus',
				action: 'Get mailbox sync status',
				description: 'Get mailbox sync status',
			},
			{
				name: 'Get Tracking Domain',
				value: 'getTrackingDomain',
				action: 'Get the tracking domain',
				description: 'Get the tracking domain',
			},
			{
				name: 'Get Warmup Ban Status',
				value: 'warmupBanStatus',
				action: 'Get warmup ban status',
			},
			{
				name: 'Hold Sending',
				value: 'hold',
				action: 'Hold sending from a mailbox',
				description: 'Hold sending from a mailbox',
			},
			{
				name: 'Pause Warmup',
				value: 'warmupPause',
				action: 'Pause warmup',
			},
			{
				name: 'Refresh Auth Check',
				value: 'refreshAuthCheck',
				action: 'Refresh the domain auth check',
				description: 'Refresh the domain auth check',
			},
			{
				name: 'Release Sending',
				value: 'release',
				action: 'Release a held mailbox',
				description: 'Release a held mailbox',
			},
			{
				name: 'Resume Warmup',
				value: 'warmupResume',
				action: 'Resume warmup',
			},
			{
				name: 'Send Email',
				value: 'send',
				action: 'Send from a mailbox',
				description: 'Send from a mailbox',
			},
			{
				name: 'Start Warmup',
				value: 'warmupStart',
				action: 'Start warmup',
			},
			{
				name: 'Stop Warmup',
				value: 'warmupStop',
				action: 'Stop warmup',
			},
			{
				name: 'Submit Warmup Appeal',
				value: 'warmupAppeal',
				action: 'Submit a warmup appeal',
				description: 'Submit a warmup appeal',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a mailbox',
				description: 'Update a mailbox',
			},
			{
				name: 'Update Behavior',
				value: 'updateBehavior',
				action: 'Update sending behavior',
				description: 'Update sending behavior',
			},
			{
				name: 'Update Tracking Domain',
				value: 'updateTrackingDomain',
				action: 'Update the tracking domain',
				description: 'Update the tracking domain',
			},
			{
				name: 'Verify Address',
				value: 'verify',
				action: 'Verify an email address',
				description: 'Verify an email address',
			},
			{
				name: 'Verify Tracking Domain',
				value: 'verifyTrackingDomain',
				action: 'Verify the tracking domain',
				description: 'Verify the tracking domain',
			},
		],
		default: 'getAll',
	},
];

export const mailboxFields: INodeProperties[] = [
	{
		displayName: 'Email IDs',
		name: 'email_ids',
		type: 'string',
		default: '',
		required: true,
		description: 'Comma-separated list.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'bulkTag',
				],
			},
		},
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'bulkTag',
				],
			},
		},
		options: [
			{
				displayName: 'Add Tags',
				name: 'add_tags',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Remove Tags',
				name: 'remove_tags',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id. The domain is derived from the mailbox address.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'authCheck',
				],
			},
		},
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'delete',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'delete',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox (email account) id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'get',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox\'s id',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'getBehavior',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox\'s id',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'getBehaviorPlan',
				],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'getAll',
				],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'getAll',
				],
				returnAll: [
					false,
				],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'getAll',
				],
			},
		},
		options: [
			{
				displayName: 'Q',
				name: 'q',
				type: 'string',
				default: '',
				description: 'Free-text search over mailbox address and name.',
			},
			{
				displayName: 'Tag',
				name: 'tag',
				type: 'string',
				default: '',
				description: 'Tag id to filter by.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'getSyncStatus',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox\'s id',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'getTrackingDomain',
				],
			},
		},
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupBanStatus',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox\'s id',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'hold',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'hold',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupPause',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupPause',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox\'s id',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'refreshAuthCheck',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'refreshAuthCheck',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox\'s id',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'release',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'release',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupResume',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupResume',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The sending mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'send',
				],
			},
		},
	},
	{
		displayName: 'To',
		name: 'to',
		type: 'string',
		default: '',
		required: true,
		description: 'Recipient addresses. Comma-separated list.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'send',
				],
			},
		},
	},
	{
		displayName: 'Subject',
		name: 'subject',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'send',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'send',
				],
			},
		},
		options: [
			{
				displayName: 'BCC',
				name: 'bcc',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Body HTML',
				name: 'body_html',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Body Plain',
				name: 'body_plain',
				type: 'string',
				default: '',
			},
			{
				displayName: 'CC',
				name: 'cc',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'In Reply To',
				name: 'in_reply_to',
				type: 'string',
				default: '',
				description: 'Message ids this email replies to. Comma-separated list.',
			},
			{
				displayName: 'Scheduled At',
				name: 'scheduled_at',
				type: 'dateTime',
				default: '',
				description: 'Required when send_mode is scheduled. Must be in the future.',
			},
			{
				displayName: 'Send Mode',
				name: 'send_mode',
				type: 'options',
				options: [
					{
						name: 'Instant',
						value: 'instant',
					},
					{
						name: 'Scheduled',
						value: 'scheduled',
					},
					{
						name: 'Smart',
						value: 'smart',
					},
				],
				default: 'instant',
				description: 'instant (default), smart (next per-mailbox scheduler gap), or scheduled (use scheduled_at).',
			},
			{
				displayName: 'Thread ID',
				name: 'thread_id',
				type: 'string',
				default: '',
				description: 'Thread id to attach the message to.',
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupStart',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupStart',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupStop',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupStop',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupAppeal',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'warmupAppeal',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Reason',
				name: 'reason',
				type: 'string',
				default: '',
				description: 'The owner\'s explanation for the appeal.',
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'update',
				],
			},
		},
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'update',
				],
			},
		},
		options: [
			{
				displayName: 'Campaign Limit',
				name: 'campaign_limit',
				type: 'number',
				default: 0,
				description: 'Daily cold-campaign cap (validated up to 100).',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Min Wait Time',
				name: 'min_wait_time',
				type: 'number',
				default: 0,
				description: 'Minimum seconds between sends.',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Display name on outgoing mail.',
			},
			{
				displayName: 'Reply To',
				name: 'reply_to',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Save To Sent',
				name: 'save_to_sent',
				type: 'boolean',
				default: false,
				description: 'SaveToSent controls the Sent folder copy on SMTP/IMAP mailboxes. Turn it off when the submission server files its own copy, or the folder ends up with two of everything.',
			},
			{
				displayName: 'Signature Code',
				name: 'signature_code',
				type: 'boolean',
				default: false,
				description: 'Treat the HTML signature as raw code.',
			},
			{
				displayName: 'Signature HTML',
				name: 'signature_html',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Signature Plain',
				name: 'signature_plain',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Signature Sync',
				name: 'signature_sync',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{
						name: 'Active',
						value: 'active',
					},
					{
						name: 'Inactive',
						value: 'inactive',
					},
					{
						name: 'Revoked',
						value: 'revoked',
					},
				],
				default: 'active',
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: '',
				description: 'Tag ids assigned to the mailbox. Comma-separated list.',
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				description: 'Timezone is the mailbox\'s own IANA zone, which its sending behaviour and business-hours window are evaluated in. Empty means not configured, so only the campaign\'s window applies.',
			},
			{
				displayName: 'Warmup',
				name: 'warmup',
				type: 'boolean',
				default: false,
				description: 'Enable or disable warmup.',
			},
			{
				displayName: 'Warmup Base',
				name: 'warmup_base',
				type: 'number',
				default: 0,
				description: 'Warmup starting volume per day.',
			},
			{
				displayName: 'Warmup Days',
				name: 'warmup_days',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Warmup End Time',
				name: 'warmup_end_time',
				type: 'string',
				default: '',
				description: 'Daily warmup window end, HH:MM.',
			},
			{
				displayName: 'Warmup Increase',
				name: 'warmup_increase',
				type: 'number',
				default: 0,
				description: 'Per-day warmup ramp increment.',
			},
			{
				displayName: 'Warmup Max',
				name: 'warmup_max',
				type: 'number',
				default: 0,
				description: 'Warmup daily ceiling.',
			},
			{
				displayName: 'Warmup Reply Rate',
				name: 'warmup_reply_rate',
				type: 'number',
				default: 0,
				description: 'Percentage of warmup threads to reply to.',
			},
			{
				displayName: 'Warmup Start Time',
				name: 'warmup_start_time',
				type: 'string',
				default: '',
				description: 'Daily warmup window start, HH:MM.',
			},
			{
				displayName: 'Warmup Tag',
				name: 'warmup_tag',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox\'s id',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'updateBehavior',
				],
			},
		},
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'updateBehavior',
				],
			},
		},
		options: [
			{
				displayName: 'Daily Limit Max',
				name: 'daily_limit_max',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Daily Limit Min',
				name: 'daily_limit_min',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Enabled',
				name: 'enabled',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Gap Max Seconds',
				name: 'gap_max_seconds',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Gap Min Seconds',
				name: 'gap_min_seconds',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Hourly Limit Max',
				name: 'hourly_limit_max',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Hourly Limit Min',
				name: 'hourly_limit_min',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Lunch Earliest',
				name: 'lunch_earliest',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Lunch Enabled',
				name: 'lunch_enabled',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Lunch Latest',
				name: 'lunch_latest',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Lunch Max Minutes',
				name: 'lunch_max_minutes',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Lunch Min Minutes',
				name: 'lunch_min_minutes',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Weekdays',
				name: 'weekdays',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Work End Max',
				name: 'work_end_max',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Work End Min',
				name: 'work_end_min',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Work Start Max',
				name: 'work_start_max',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Work Start Min',
				name: 'work_start_min',
				type: 'number',
				default: 0,
			},
		],
	},
	{
		displayName: 'Mailbox ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox id.',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'updateTrackingDomain',
				],
			},
		},
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'updateTrackingDomain',
				],
			},
		},
		options: [
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: '',
				description: 'The custom tracking subdomain (for example t.acme.com). Empty clears it.',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'verify',
				],
			},
		},
		options: [
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				description: 'The address to verify.',
				placeholder: 'name@email.com',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				description: 'The address to verify.',
				placeholder: 'name@email.com',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The mailbox\'s id',
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'verifyTrackingDomain',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'mailbox',
				],
				operation: [
					'verifyTrackingDomain',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
];
