import type { INodeProperties } from 'n8n-workflow';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const oauthAppOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
			},
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create an OAuth application',
				description: 'Create an OAuth application',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete an OAuth application',
				description: 'Delete an OAuth application',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get an OAuth application',
				description: 'Get an OAuth application',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many OAuth applications',
				description: 'Get many OAuth applications',
			},
			{
				name: 'Get Webhook Deliveries',
				value: 'getWebhookDeliveries',
				action: 'Get many webhook deliveries',
				description: 'Get many webhook deliveries',
			},
			{
				name: 'Get Webhook Endpoints',
				value: 'getWebhookEndpoints',
				action: 'Get many webhook endpoints',
				description: 'Get many webhook endpoints',
			},
			{
				name: 'Get Webhook Secret',
				value: 'getWebhookSecret',
				action: 'Get the webhook signing secret',
				description: 'Get the webhook signing secret',
			},
			{
				name: 'Rotate Secret',
				value: 'rotateSecret',
				action: 'Rotate the client secret',
				description: 'Rotate the client secret',
			},
			{
				name: 'Rotate Webhook Secret',
				value: 'rotateWebhookSecret',
				action: 'Rotate the webhook signing secret',
				description: 'Rotate the webhook signing secret',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update an OAuth application',
				description: 'Update an OAuth application',
			},
			{
				name: 'Upload Logo',
				value: 'uploadLogo',
				action: 'Upload an application logo',
				description: 'Upload an application logo',
			},
		],
		default: 'getAll',
	},
];

export const oauthAppFields: INodeProperties[] = [
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'create',
				],
			},
		},
		options: [
			{
				displayName: 'Allowed Webhook Domains',
				name: 'allowed_webhook_domains',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Logo URL',
				name: 'logo_url',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Application name',
			},
			{
				displayName: 'Redirect Uris',
				name: 'redirect_uris',
				type: 'string',
				default: '',
				description: 'Allowed redirect URIs. Comma-separated list.',
			},
			{
				displayName: 'Scopes',
				name: 'scopes',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Webhook Events',
				name: 'webhook_events',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Webhook URL',
				name: 'webhook_url',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Website URL',
				name: 'website_url',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The application\'s id',
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'delete',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'delete',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The application\'s id',
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'get',
				],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'getWebhookDeliveries',
				],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'getWebhookDeliveries',
				],
				returnAll: [
					false,
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'getWebhookDeliveries',
				],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'getWebhookDeliveries',
				],
			},
		},
		options: [
			{
				displayName: 'Event Type',
				name: 'event_type',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'getWebhookEndpoints',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'getWebhookSecret',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The application\'s id',
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'rotateSecret',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'rotateSecret',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'rotateWebhookSecret',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'rotateWebhookSecret',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The application\'s id',
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'update',
				],
			},
		},
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'update',
				],
			},
		},
		options: [
			{
				displayName: 'Allowed Webhook Domains',
				name: 'allowed_webhook_domains',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Logo URL',
				name: 'logo_url',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Redirect Uris',
				name: 'redirect_uris',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Scopes',
				name: 'scopes',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Webhook Events',
				name: 'webhook_events',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Webhook URL',
				name: 'webhook_url',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Website URL',
				name: 'website_url',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Input Binary Field',
		name: 'binaryPropertyName',
		type: 'string',
		default: 'data',
		required: true,
		description: 'The name of the input binary field holding the file to upload',
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'uploadLogo',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'oauthApp',
				],
				operation: [
					'uploadLogo',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
];
