import type { INodeProperties } from 'n8n-workflow';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const segmentOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
			},
		},
		options: [
			{
				name: 'Add to Campaign',
				value: 'addToCampaign',
				action: 'Add a segment to a campaign',
				description: 'Add a segment to a campaign',
			},
			{
				name: 'Create',
				value: 'create',
				action: 'Create a segment',
				description: 'Create a segment',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a segment',
				description: 'Delete a segment',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a segment',
				description: 'Get a segment',
			},
			{
				name: 'Get Fields',
				value: 'getFields',
				action: 'Get the segment condition fields',
				description: 'Get the segment condition fields',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many segments',
				description: 'Get many segments',
			},
			{
				name: 'Get Overrides',
				value: 'getOverrides',
				action: 'Get manual membership overrides',
				description: 'Get manual membership overrides',
			},
			{
				name: 'Look Up Members',
				value: 'lookupMembers',
				action: 'Look up membership modes',
				description: 'Look up membership modes',
			},
			{
				name: 'Preview',
				value: 'preview',
				action: 'Preview an unsaved segment',
				description: 'Preview an unsaved segment',
			},
			{
				name: 'Set Members',
				value: 'setMembers',
				action: 'Set manual segment members',
				description: 'Set manual segment members',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a segment',
				description: 'Update a segment',
			},
		],
		default: 'getAll',
	},
];

export const segmentFields: INodeProperties[] = [
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The segment\'s id',
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'addToCampaign',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'addToCampaign',
				],
			},
		},
		options: [
			{
				displayName: 'Campaign ID',
				name: 'campaign_id',
				type: 'string',
				default: '',
				description: 'The campaign to add them to',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'create',
				],
			},
		},
		options: [
			{
				displayName: 'Color',
				name: 'color',
				type: 'color',
				default: '',
			},
			{
				displayName: 'Conditions',
				name: 'conditions',
				type: 'json',
				default: '',
				description: 'Provide as JSON.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				description: 'What the segment is for',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Match',
				name: 'match',
				type: 'options',
				options: [
					{
						name: 'All',
						value: 'all',
					},
					{
						name: 'Any',
						value: 'any',
					},
				],
				default: 'all',
				description: 'all or any',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Segment name',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The segment\'s id',
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'delete',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'delete',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The segment\'s id',
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'get',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The segment\'s id',
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'getOverrides',
				],
			},
		},
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'lookupMembers',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'lookupMembers',
				],
			},
		},
		options: [
			{
				displayName: 'Contacts',
				name: 'contacts',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'preview',
				],
			},
		},
		options: [
			{
				displayName: 'Conditions',
				name: 'conditions',
				type: 'json',
				default: '',
				description: 'Provide as JSON.',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Match',
				name: 'match',
				type: 'options',
				options: [
					{
						name: 'All',
						value: 'all',
					},
					{
						name: 'Any',
						value: 'any',
					},
				],
				default: 'all',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The segment\'s id',
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'setMembers',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'setMembers',
				],
			},
		},
		options: [
			{
				displayName: 'Contacts',
				name: 'contacts',
				type: 'string',
				default: '',
				description: 'Comma-separated list.',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Mode',
				name: 'mode',
				type: 'options',
				options: [
					{
						name: 'Auto',
						value: 'auto',
					},
					{
						name: 'Exclude',
						value: 'exclude',
					},
					{
						name: 'Include',
						value: 'include',
					},
				],
				default: 'include',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The segment\'s id',
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'update',
				],
			},
		},
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'segment',
				],
				operation: [
					'update',
				],
			},
		},
		options: [
			{
				displayName: 'Color',
				name: 'color',
				type: 'color',
				default: '',
			},
			{
				displayName: 'Conditions',
				name: 'conditions',
				type: 'json',
				default: '',
				description: 'Provide as JSON.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				description: 'What the segment is for',
			},
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Match',
				name: 'match',
				type: 'options',
				options: [
					{
						name: 'All',
						value: 'all',
					},
					{
						name: 'Any',
						value: 'any',
					},
				],
				default: 'all',
				description: 'all or any',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Segment name',
			},
		],
	},
];
