import type { INodeProperties } from 'n8n-workflow';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const suppressionOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [
					'suppression',
				],
			},
		},
		options: [
			{
				name: 'Add',
				value: 'add',
				action: 'Add suppression entries',
				description: 'Add suppression entries',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many suppression entries',
				description: 'Get many suppression entries',
			},
			{
				name: 'Remove',
				value: 'remove',
				action: 'Remove a suppression entry',
				description: 'Remove a suppression entry',
			},
		],
		default: 'getAll',
	},
];

export const suppressionFields: INodeProperties[] = [
	{
		displayName: 'Entries',
		name: 'entries',
		type: 'json',
		default: '',
		required: true,
		description: 'Provide as JSON.',
		displayOptions: {
			show: {
				resource: [
					'suppression',
				],
				operation: [
					'add',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'suppression',
				],
				operation: [
					'add',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
			{
				displayName: 'Reason',
				name: 'reason',
				type: 'string',
				default: '',
				description: 'Reason applies to every entry that does not carry its own.',
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: {
			show: {
				resource: [
					'suppression',
				],
				operation: [
					'getAll',
				],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: {
				resource: [
					'suppression',
				],
				operation: [
					'getAll',
				],
				returnAll: [
					false,
				],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'suppression',
				],
				operation: [
					'getAll',
				],
			},
		},
		options: [
			{
				displayName: 'Q',
				name: 'q',
				type: 'string',
				default: '',
				description: 'Substring filter on the address or domain.',
			},
		],
	},
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		required: true,
		description: 'The suppression entry\'s id',
		displayOptions: {
			show: {
				resource: [
					'suppression',
				],
				operation: [
					'remove',
				],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: [
					'suppression',
				],
				operation: [
					'remove',
				],
			},
		},
		options: [
			{
				displayName: 'Idempotency Key',
				name: 'idempotencyKey',
				type: 'string',
				default: '',
				description: 'Optional client-generated key (1 to 255 chars). Retrying with the same key returns the original result instead of acting twice.',
			},
		],
	},
];
