import type { INodeProperties } from 'n8n-workflow';

// AUTO-GENERATED by scripts/generate-node.mjs. Edit spec/node-overlay.json instead.
export const workspaceOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: [
					'workspace',
				],
			},
		},
		options: [
			{
				name: 'Get Identity',
				value: 'getIdentity',
				action: 'Get the caller identity',
				description: 'Get the caller identity',
			},
			{
				name: 'Get Plans',
				value: 'getPlans',
				action: 'List plans',
				description: 'List plans',
			},
			{
				name: 'Get Timezones',
				value: 'getTimezones',
				action: 'List timezones',
				description: 'List timezones',
			},
		],
		default: 'getPlans',
	},
];

export const workspaceFields: INodeProperties[] = [
];
